# Generated by Django 3.1.2 on 2021-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_id', models.CharField(max_length=100)),
                ('char_type', models.CharField(max_length=20)),
                ('char_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_id', models.CharField(max_length=100)),
                ('par_body', models.TextField()),
                ('par_is_root', models.BooleanField(default=False)),
                ('par_is_end', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ParagraphLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('par_from_id', models.CharField(max_length=100)),
                ('par_to_id', models.CharField(max_length=100)),
            ],
        ),
    ]
