# Generated by Django 3.1.2 on 2021-10-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParagraphModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itm_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='character',
            old_name='char_id',
            new_name='chr_id',
        ),
        migrations.RemoveField(
            model_name='character',
            name='char_name',
        ),
        migrations.RemoveField(
            model_name='character',
            name='char_type',
        ),
    ]
