# Generated by Django 3.1.2 on 2021-01-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WriterModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintextbody',
            name='text_id',
            field=models.IntegerField(default=0),
        ),
    ]
